# Generated by bower2nix v3.1.1 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "vaadin-grid" "2.0.0" "v2.0.0" "0n5k4724ks81ascwwzpk36gqpq8w7av39s3iqxji0krwhs4hw46m")
  (fetchbower "polymer" "1.9.1" "^1.6.1" "1nvq9sxbqdlmxpzcy4sic2awrhnx7jv738gll8c4s0xd69bcqmjd")
  (fetchbower "iron-resizable-behavior" "PolymerElements/iron-resizable-behavior#1.0.6" "PolymerElements/iron-resizable-behavior#^1.0.5" "1rgzlg4a5212i58cmnshg52ad1abl9s0kg41i6jp50462n96xh6a")
  (fetchbower "iron-scroll-target-behavior" "PolymerElements/iron-scroll-target-behavior#1.1.1" "PolymerElements/iron-scroll-target-behavior#^1.1.0" "0dqifhmscp7fg7hn7nr9lj7q6248rn97zksinphvpa6splb62270")
  (fetchbower "iron-a11y-keys-behavior" "1.1.9" "^1.1.9" "01cnxv03wncg9p7yx5vdlpfp1blincamrw7y8j1bdsjvrchbl93f")
  (fetchbower "iron-a11y-announcer" "1.0.6" "^1.0.5" "10lc1c34j1wx5fwp2kmc76mbxr9mskykblc6b2qwgmzyysdln81c")
  (fetchbower "webcomponentsjs" "0.7.24" "^0.7.24" "0k3yajz8d9whg4fnrjsy03ajf2q9qgjwg02g8x47vprzqv2c9qi0")
]; }
